/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HeadLine: (typeof import('./src/components/HeadLine.vue'))['default'];
    PlayGround: (typeof import('./src/components/PlayGround.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    VanButton: (typeof import('vant/es'))['Button'];
    VanCol: (typeof import('vant/es'))['Col'];
    VanField: (typeof import('vant/es'))['Field'];
    VanPopup: (typeof import('vant/es'))['Popup'];
    VanRow: (typeof import('vant/es'))['Row'];
    VanSpace: (typeof import('vant/es'))['Space'];
    VanSticky: (typeof import('vant/es'))['Sticky'];
    VideoList: (typeof import('./src/components/VideoList.vue'))['default'];
    WebFooter: (typeof import('./src/components/WebFooter.vue'))['default'];
    WebHeader: (typeof import('./src/components/WebHeader.vue'))['default'];
    WebStart: (typeof import('./src/components/WebStart.vue'))['default'];
  }
}
